#ifndef HTTP_RESPONSE_H
#define HTTP_RESPONSE_H

#include <stddef.h>
#include "startline.h"
#include "request.h"
#include "config.h"
// we include request.h since there's some common things
// such as the content maxlen

typedef enum {
	CONTENT_ENCODING_NONE,
	CONTENT_ENCODING_GZIP,
} ContentEncoding;

typedef struct {
	ContentEncoding encoding;
	size_t bodyLen;
	// body should ALWAYS be treated as binary data, except in directory browsing and 404 responses where it's convenient to treat it as a string since it's generated by us and we know it will be null terminated
	uint8_t body[CONTENT_MAXLEN];
	char fileName[SITE_PATH_MAX];
	StatusLine *statusLine;
	struct hashmap *headers;
} HttpResponse;

HttpResponse *initializeResponse();

void freeResponse(HttpResponse *response);

void sendStatusLine(HttpResponse *response, int clientfd);
void sendHeaders(HttpResponse *response, int clientfd);
void sendBody(HttpResponse *response, int clientfd);

void generateResponse(HttpResponse *response, HttpRequest *request, ServerConfig *cfg);

#endif
